[General]
discordUrl=https://discord.com
csfFile = generalmd.csf
# Boot as Yuri's Revenge ("ra2" to revert)
engine = yr

# Where game resources are located
gameresBaseUrl=/cdn/game-res/v2/
mapsBaseUrl=/cdn/maps/
modsBaseUrl=/cdn/mods/
gameResArchiveUrl=
patchNotesUrl=//www.ra2web.com/patch-notes.html
ladderRulesUrl=//www.ra2web.com/ladder-rules.html
modSdkUrl=https://github.com/ra2web/mod-sdk
breakingNewsUrl=/breaking-news.html
oldClientsBaseUrl=/old/
quickMatchEnabled=yes
botsEnabled=yes
debugLogging=wol
defaultLanguage=en-US

viewport.width=1024
viewport.height=768
